version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9
    working_directory: ~/creature-features
    steps:
      - checkout

      - run: npm install
      - run: npm run lint
      # run tests!
      - run: npm test

